# Importando dados com Pandas - Arquivo CSV

In [1]:
import pandas as pd

base_clientes = pd.read_csv('BaseClientes.csv', delimiter=',')

In [6]:
base_clientes

          nome   sobrenome  idade  ultimo_salario empresa_atual
0       Enrico    Rushmare   31.0             NaN        Skinte
1        Ivett   Pettiward   31.0         5249.72           NaN
2    Stillmann      Budnik    NaN        13738.43      Tagchatx
3       Zondra       Lille   18.0        15998.02         Roomm
4        Eldon  Normansell   32.0             NaN           NaN
..         ...         ...    ...             ...           ...
995     Darrel     Finders   19.0        19447.05     Jaxnation
996     Nelson       Pedel   20.0         3112.77           NaN
997   Emmanuel  Trevithick    NaN         4383.58       Twinder
998       Alfy     Ilyunin   46.0             NaN        Vinder
999    Phaidra      Dolley   20.0             NaN     Bubblemix

[1000 rows x 5 columns]

**Referências:**

Wikipedia, **pandas (software).** Disponível em: < https://pt.wikipedia.org/wiki/Pandas_(software) >. Acesso em: 05 mai. 2021.  <br/>
Pandas, **User Guide.** Disponível em: < https://pandas.pydata.org/docs/user_guide/index.html >.  Acesso em: 05 mai. 2021.  <br/>
Pandas, **pandas.read_csv().** Disponível em: < https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv >. Acesso em: 05 mai. 2021.